name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Lint
        run: yarn lint
      - name: Jest Tests
        run: yarn test
      - name: Typescript build
        run: yarn build
