name: Publish Storybook

on: [push]

# on:
#     push:
#         branches:
#             - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Yarn Install
        run: yarn install

      - name: Deploy Storybook
        run: yarn storybook-to-ghpages --ci --host-token-env-variable=ACCESS_TOKEN
